// react/TodoList.jsx
import React, { useState } from "react";

export default function TodoList() {
  const [todos, setTodos] = useState(["Learn Angular", "Build a transpiler"]);
  const [newTodo, setNewTodo] = useState("");

  const addTodo = () => {
    if (newTodo.trim()) {
      setTodos([...todos, newTodo]);
      setNewTodo("");
    }
  };

  return (
    <div>
      <h1>Todo List</h1>

      <ul>
        {todos.map((todo, idx) => (
          <li key={idx}>{todo}</li>
        ))}
      </ul>

      <input
        type="text"
        value={newTodo}
        onChange={(e) => setNewTodo(e.target.value)}
      />

      <button onClick={addTodo}>Add Todo</button>
    </div>
  );
}

// angular_output/TodoList.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-todo-list',
  templateUrl: './TodoList.component.html'
})
export class TodoListComponent {
  todos: string[] = ['Learn Angular', 'Build a transpiler'];
  newTodo: string = '';

  addTodo() {
    if (this.newTodo.trim()) {
      this.todos.push(this.newTodo);
      this.newTodo = '';
    }
  }
}

<div>
      <h1>Todo List</h1>

      <ul>
        <li *ngFor="let todo of todos">{{ todo }}</li>
      </ul>

      <input
        type="text"
        [(ngModel)]="newTodo"
        
      />

      <button (click)="addTodo()">Add Todo</button>
    </div>
